[2025-08-22T03:35:18.762+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:34:59.450025+00:00 [queued]>
[2025-08-22T03:35:18.768+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:34:59.450025+00:00 [queued]>
[2025-08-22T03:35:18.768+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-22T03:35:18.774+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-08-22 03:34:59.450025+00:00
[2025-08-22T03:35:18.779+0000] {standard_task_runner.py:57} INFO - Started process 355 to run task
[2025-08-22T03:35:18.782+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'retrain_model', 'manual__2025-08-22T03:34:59.450025+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmprs_nbzkn']
[2025-08-22T03:35:18.783+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask retrain_model
[2025-08-22T03:35:18.802+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-22T03:34:59.450025+00:00 [running]> on host 1dcd02618b5d
[2025-08-22T03:35:18.833+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T03:34:59.450025+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T03:34:59.450025+00:00'
[2025-08-22T03:35:18.834+0000] {logging_mixin.py:151} INFO - ‚ùå Error durante el entrenamiento y registro del modelo: name 'setup_mlflow_environment' is not defined
[2025-08-22T03:35:18.834+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 313, in retrain_model
    raise e
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 279, in retrain_model
    if not setup_mlflow_environment():
NameError: name 'setup_mlflow_environment' is not defined
[2025-08-22T03:35:18.838+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_ml_pipeline, task_id=retrain_model, execution_date=20250822T033459, start_date=20250822T033518, end_date=20250822T033518
[2025-08-22T03:35:18.841+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task retrain_model (name 'setup_mlflow_environment' is not defined; 355)
[2025-08-22T03:35:18.880+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-22T03:35:18.890+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
