[2025-08-22T03:35:18.744+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model scheduled__2025-08-21T21:34:51.175106+00:00 [queued]>
[2025-08-22T03:35:18.749+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model scheduled__2025-08-21T21:34:51.175106+00:00 [queued]>
[2025-08-22T03:35:18.750+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-22T03:35:18.757+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-08-21 21:34:51.175106+00:00
[2025-08-22T03:35:18.764+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2025-08-22T03:35:18.766+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'retrain_model', 'scheduled__2025-08-21T21:34:51.175106+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmpe1px_iph']
[2025-08-22T03:35:18.767+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask retrain_model
[2025-08-22T03:35:18.789+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_ml_pipeline.retrain_model scheduled__2025-08-21T21:34:51.175106+00:00 [running]> on host 1dcd02618b5d
[2025-08-22T03:35:18.815+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T21:34:51.175106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-21T21:34:51.175106+00:00'
[2025-08-22T03:35:18.816+0000] {logging_mixin.py:151} INFO - ‚ùå Error durante el entrenamiento y registro del modelo: name 'setup_mlflow_environment' is not defined
[2025-08-22T03:35:18.816+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 313, in retrain_model
    raise e
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 279, in retrain_model
    if not setup_mlflow_environment():
NameError: name 'setup_mlflow_environment' is not defined
[2025-08-22T03:35:18.820+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_ml_pipeline, task_id=retrain_model, execution_date=20250821T213451, start_date=20250822T033518, end_date=20250822T033518
[2025-08-22T03:35:18.829+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task retrain_model (name 'setup_mlflow_environment' is not defined; 354)
[2025-08-22T03:35:18.863+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-22T03:35:18.872+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
