[2025-08-21T18:23:39.496+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-21T18:23:29.548151+00:00 [queued]>
[2025-08-21T18:23:39.500+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-21T18:23:29.548151+00:00 [queued]>
[2025-08-21T18:23:39.500+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-21T18:23:39.506+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-08-21 18:23:29.548151+00:00
[2025-08-21T18:23:39.509+0000] {standard_task_runner.py:57} INFO - Started process 305 to run task
[2025-08-21T18:23:39.510+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'retrain_model', 'manual__2025-08-21T18:23:29.548151+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmpi3jtlrua']
[2025-08-21T18:23:39.511+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask retrain_model
[2025-08-21T18:23:39.528+0000] {task_command.py:415} INFO - Running <TaskInstance: crypto_ml_pipeline.retrain_model manual__2025-08-21T18:23:29.548151+00:00 [running]> on host 7e37d9eb2ca7
[2025-08-21T18:23:39.554+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-08-21T18:23:29.548151+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-21T18:23:29.548151+00:00'
[2025-08-21T18:23:39.555+0000] {logging_mixin.py:151} INFO - ü§ñ Retraining ML model...
[2025-08-21T18:23:39.592+0000] {logging_mixin.py:151} INFO - üìä Training data shape: (929, 16)
[2025-08-21T18:23:39.615+0000] {logging_mixin.py:151} WARNING - 2025/08/21 18:23:39 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-08-21T18:23:39.637+0000] {logging_mixin.py:151} INFO - ‚è≥ Training model...
[2025-08-21T18:23:49.674+0000] {credentials.py:1123} INFO - Found credentials in environment variables.
[2025-08-21T18:23:49.836+0000] {logging_mixin.py:151} INFO - ‚úÖ Model training completed. Run ID: 1c7c200a837a453db0aff1c30e6acca5
[2025-08-21T18:23:49.841+0000] {logging_mixin.py:151} WARNING - 2025/08/21 18:23:49 INFO mlflow.tracking._tracking_service.client: üèÉ View run nebulous-crab-891 at: http://mlflow:5000/#/experiments/1/runs/1c7c200a837a453db0aff1c30e6acca5.
[2025-08-21T18:23:49.841+0000] {logging_mixin.py:151} WARNING - 2025/08/21 18:23:49 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-08-21T18:23:49.847+0000] {python.py:194} INFO - Done. Returned value was: {'run_id': '1c7c200a837a453db0aff1c30e6acca5', 'mse': 0.0016482454167834676, 'mae': 0.012017852125539758, 'training_date': '2025-08-21'}
[2025-08-21T18:23:49.855+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=crypto_ml_pipeline, task_id=retrain_model, execution_date=20250821T182329, start_date=20250821T182339, end_date=20250821T182349
[2025-08-21T18:23:49.879+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-21T18:23:49.886+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
