[2025-08-22T11:09:43.350+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_ml_pipeline.process_crypto_data manual__2025-08-22T11:09:33.679498+00:00 [queued]>
[2025-08-22T11:09:43.355+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_ml_pipeline.process_crypto_data manual__2025-08-22T11:09:33.679498+00:00 [queued]>
[2025-08-22T11:09:43.355+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-08-22T11:09:43.359+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): process_crypto_data> on 2025-08-22 11:09:33.679498+00:00
[2025-08-22T11:09:43.364+0000] {standard_task_runner.py:57} INFO - Started process 264 to run task
[2025-08-22T11:09:43.366+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_ml_pipeline', 'process_crypto_data', 'manual__2025-08-22T11:09:33.679498+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/crypto_ml_pipeline.py', '--cfg-path', '/tmp/tmpugfh0syz']
[2025-08-22T11:09:43.368+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask process_crypto_data
[2025-08-22T11:09:43.388+0000] {task_command.py:416} INFO - Running <TaskInstance: crypto_ml_pipeline.process_crypto_data manual__2025-08-22T11:09:33.679498+00:00 [running]> on host 89f10e135bc4
[2025-08-22T11:09:43.413+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='crypto-mlops' AIRFLOW_CTX_DAG_ID='crypto_ml_pipeline' AIRFLOW_CTX_TASK_ID='process_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-22T11:09:33.679498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-22T11:09:33.679498+00:00'
[2025-08-22T11:09:43.414+0000] {logging_mixin.py:151} INFO - ‚öôÔ∏è Processing crypto data...
[2025-08-22T11:09:43.427+0000] {logging_mixin.py:151} INFO - üì• Downloaded data from MinIO: 4 symbols
[2025-08-22T11:09:43.440+0000] {logging_mixin.py:151} INFO - ‚úÖ Processed 929 clean records for BTC_USDT
[2025-08-22T11:09:43.445+0000] {logging_mixin.py:151} INFO - ‚úÖ Processed 929 clean records for ETH_USDT
[2025-08-22T11:09:43.449+0000] {logging_mixin.py:151} INFO - ‚úÖ Processed 929 clean records for BNB_USDT
[2025-08-22T11:09:43.454+0000] {logging_mixin.py:151} INFO - ‚úÖ Processed 929 clean records for ADA_USDT
[2025-08-22T11:09:43.476+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/crypto_ml_pipeline.py", line 126, in process_crypto_data
    minio_client.make_bucket(processed_bucket)
  File "/home/airflow/.local/lib/python3.11/site-packages/minio/api.py", line 623, in make_bucket
    self._url_open(
  File "/home/airflow/.local/lib/python3.11/site-packages/minio/api.py", line 391, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /processed-data, request_id: 185E1242F1E72612, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: processed-data
[2025-08-22T11:09:43.481+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=crypto_ml_pipeline, task_id=process_crypto_data, execution_date=20250822T110933, start_date=20250822T110943, end_date=20250822T110943
[2025-08-22T11:09:43.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task process_crypto_data (S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /processed-data, request_id: 185E1242F1E72612, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: processed-data; 264)
[2025-08-22T11:09:43.504+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-22T11:09:43.515+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
